# Generated by Django 3.2.12 on 2024-05-24 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsapp', '0004_news'),
        ('employeeapp', '0009_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('priority', models.CharField(max_length=300)),
                ('ndatetime', models.DateTimeField(auto_now=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsapp.project')),
            ],
        ),
    ]
