# Generated by Django 3.2.12 on 2024-05-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0011_requirements_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='requirements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeapp.requirements'),
            preserve_default=False,
        ),
    ]
