# Generated by Django 3.2.12 on 2024-05-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0012_testcase_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='requirements',
            field=models.CharField(max_length=350),
        ),
    ]
