# Generated by Django 3.2.12 on 2024-05-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0013_alter_testcase_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='priority',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='teststeps',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='date_of_creation',
            field=models.DateField(auto_now=True),
        ),
    ]
