# Generated by Django 3.2.12 on 2024-05-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0014_auto_20240528_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='comments',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
