# Generated by Django 3.2.12 on 2024-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0016_auto_20240528_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='developer_email',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
